language: python

python:
  - 2.7

install:
  - pip install flake8
  - pip install -e .

script:
  - flake8 --max-line-length=100 --max-complexity=24 --statistics --benchmark --ignore=E1,E2,E4,E501,F4 symposion
